In [2]:
import numpy as np

用 arange 函数创建数组,并获取其数据类型

In [6]:
a=np.arange(5)
print(a.dtype)
print(a)
print(a.shape)

int64
[0 1 2 3 4]
(5,)


创建多维的NumPy数组,并查看其维度

In [5]:
m= np.array([np.arange(2), np.arange(2)])
m
print(m.shape)

创建3×3的多维数组，查看其维度，选取数组元素

In [6]:
x=np.array([np.arange(3), np.arange(3), np.arange(3)])
print(x)
print(x.shape)
print(x[2,2])

NumPy数组中的每一个元素均为相同的数据类型
  
类型 | 描述
-----|-----
bool | 用一位存储的布尔类型(值为 TRUE 或 FALSE )
inti | 由所在平台决定其精度的整数(一般为 int32 或 int64 )
int8 | 整数,范围为-128至127
int16 | 整数,范围为-32768至32767
int32 | 整数,范围为-2^31 至2^31-1
int64 | 整数,范围为-2^63 至2^63-1
uint8 | 无符号整数,范围为0至255
uint16 | 无符号整数,范围为0至65535
uint32 | 无符号整数,范围为0至2^32-1
uint64 | 无符号整数,范围为0至2^64-1
float16 | 半精度浮点数(16位):其中用1位表示正负号,5位表示指数,10位表示尾数
float32 | 单精度浮点数(32位):其中用1位表示正负号,8位表示指数,23位表示尾数
float64 或 float | 双精度浮点数(64位):其中用1位表示正负号,11位表示指数,52位表示尾数
complex64 | 复数,分别用两个32位浮点数表示实部和虚部
complex128 或 complex | 复数,分别用两个64位浮点数表示实部和虚部

itemsize 属性:单个数组元素在内存中占用的字节数  


In [7]:
b = np.arange(7, dtype=np.uint16)
print(b)
print(b.dtype)
print(b.dtype.itemsize)

可以用字符编码来表示数据类型  

数据类型 | 字符编码
--------|--------
整数 | i
无符号整数 | u
单精度浮点数 | f
双精度浮点数 | d
布尔值 | b
复数 | D
字符串 | S
unicode字符串 | U
void (空) | V


In [8]:
c=np.arange(3, 4, 0.1, dtype='f')
print(c)

将两个字符作为参数传给数据类型的构造函数。  
此时,第一个字符表示数据类型,第二个字符表示该类型在内存中占用的字节数(2、4、8分别代表精度为16、32、64位的浮点数)

In [9]:
np.dtype('f2')

完整的NumPy数据类型列表可以在 sctypeDict.keys() 中找到

In [10]:
np.sctypeDict.keys()

---
# 自定义数据类型

创建自定义数据类型  
用一个长度为40个字符的字符串来记录商品名称，  
用一个32位的整数来记录商品的库存数量，  
最后用一个32位的单精度浮点数来记录商品价格  

字节序是指位长为32或64的字(word)存储的顺序,包括大端序big-endian)和小端序(little-endian)。大端序是将最高位字节存储在最低的内存地址处,用 > 表示;与之相反,小端序是将最低位字节存储在最低的内存地址处,用 < 表示

In [11]:
t = np.dtype([('name', np.str, 40), ('numitems', np.int32), ('price', np.float32)])
print(t)

查看数据类型

In [12]:
print(t['name'])

用 array 函数创建数组，并指定数据类型（默认为浮点数）

In [13]:
itemz = np.array([('Meaning of life DVD', 42, 3.14), ('Butter', 13, 2.72)], dtype=t)
print(itemz)
print(itemz[1])

---
# 多维数组的切片和索引

ndarray 支持在多维数组上的切片操作。


创建一个数组并改变其维度,使之变成一个三维数组  

reshape 函数的作用是改变数组的“形状”,也就是改变数组的维度,其参数为一个正整数元组,分别指定数组在每个维度上的大小  
为了方便起见,我们可以用一个省略号( ... )来表示遍历剩下的维度。

In [3]:
b = np.arange(96).reshape(8,3,4)
print(b)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]]

 [[36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]

 [[48 49 50 51]
  [52 53 54 55]
  [56 57 58 59]]

 [[60 61 62 63]
  [64 65 66 67]
  [68 69 70 71]]

 [[72 73 74 75]
  [76 77 78 79]
  [80 81 82 83]]

 [[84 85 86 87]
  [88 89 90 91]
  [92 93 94 95]]]


## 切片操作

In [15]:
print(b.shape)
print(b[0,:,:])
print(b[1, ...])

In [16]:
print(b[3,1])
print(b[3,1,::2])   #在上面的数组切片中间隔地选定元素
print(b[...,2])
print(b[:,2])
print(b[0,:,2])

In [18]:
print(b[:,:,-1])  #最后一列


In [20]:
print(b[:,::-1,-1])  #反向选取最后一列

In [21]:
print(b[::-1])    #翻转一维数组
print(b[...,::-1])

# 改变数组的维度
.ravel()    .flatten()  展平  
.shape()    用元组设置维度  
.transpose()    转置矩阵  
.reshape()    .resoze() 改变数组维度

In [4]:
b.ravel()   #展平

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95])

In [23]:
b.flatten() #flatten 函数会请求分配内存来保存结果,而 ravel 函数只是返回数组的一个视图

In [25]:
b.shape = (24,4)    #用元组设置维度
                    #这样的做法将直接改变所操作的数组
b

In [26]:
b.transpose()   #转置矩阵

In [27]:
b.resize((8,3,4))   #resize 和 reshape 函数的功能一样
                    #resize 会直接修改所操作的数组
b

# 组合数组  
np.hstack() np.concatenate(axis=1)  水平组合  
np.vstack() np.concatenate(axis=0)  垂直组合  
np.dstack() 深度组合  
np.column_stack()   列组合  
np.row_stack()  行组合

In [7]:
a = np.arange(9).reshape(3,3)
b = 2 * a
c = 2 * b
d = 2 * c
print(a)
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]


In [30]:
np.hstack((a,b))   #水平组合
                   #将 ndarray 对象构成的元组作为参数,传给hstack 函数

In [41]:
np.concatenate((a,b,c,d), axis=1)   #concatenate 函数来实现同样的效果

In [42]:
np.vstack((a,b))    #垂直组合

In [43]:
np.concatenate((a,b,c,d), axis=0)

In [44]:
np.dstack((a,b))     #深度组合
                     #将一系列数组沿着纵轴(深度)方向进行层叠组合
                     #相同的元组作为参数传给 dstack 函数

In [47]:
oned = np.arange(3)
twice_oned = 2 * oned
np.column_stack((oned, twice_oned)) #列组合
                                    #对于一维数组将按列方向进行组合

In [49]:
np.column_stack((a,b)) == np.hstack((a,b)) #对于二维数组, column_stack 与 hstack 的效果是相同的

In [50]:
np.row_stack((oned, twice_oned))    #行组合
                                    #一维数组,将直接层叠起来组合成一个二维数组

In [52]:
np.row_stack((a,b)) == np.vstack((a,b))    #对于二维数组, row_stack 与 vstack 的效果是相同的

# 数组分割
np.hsplit() np.split(axis=1)    水平分割  
np.vsplit() np.split(axis=0)    垂直分割  
np.dsplit() 深度分割

In [54]:
np.hsplit(a, 3) #水平分割
                #把数组沿着水平方向分割为3个相同大小的子数组

In [59]:
np.split(a, 3, axis=1)

In [57]:
np.vsplit(a, 3) #垂直分割
                #将把数组沿着垂直方向分割

In [8]:
np.split(a,3,axis=0)

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

In [66]:
e = np.arange(27).reshape(3,3,3)
print(e)

np.dsplit(e,3)  #深度分割
                #将按深度方向分割数组

# 数组的属性、
.ndim   
.size   
.itemsize   
.nbytes     
.T  
.real   
.imag   
.flat   

In [69]:
print(a)
a.ndim  #ndim 属性,给出数组的维数,或数组轴的个数

In [70]:
a.size  #size 属性,给出数组元素的总个数

In [71]:
a.itemsize  #itemsize 属性,给出数组中的元素在内存中所占的字节数

In [72]:
a.nbytes    #nbytes 属性,整个数组所占的存储空间
            #itemsize 和 size 属性值的乘积

In [73]:
a.T #T 属性, 矩阵转置
    #效果和 transpose 函数一样
    #对于一维数组,其 T 属性就是原数组

In [6]:
f = np.array([1.j + 2, 3.j + 4])
print(f)
f.real  #real 属性,给出复数数组的实部

In [7]:
f.imag  #imag 属性,给出复数数组的虚部

In [27]:
g = b.flat  #flat 属性, 将返回一个 numpy.flatiter 对象
                                    #这是获得 flatiter 对象的唯一方式——我们无法访问 flatiter 的构造函数
print(g)

In [28]:
for item in g:  #这个所谓的“扁平迭代器”可以让我们像遍历一维数组一样去遍历任意的多维数组
    print(item)

In [34]:
print(b.flat[2])    #用 flatiter 对象直接获取一个数组元素
print(b.flat[[0,2]])    #或者获取多个元素

In [37]:
b.flat[[0,2]] = 7   #flat 属性是一个可赋值的属性。对 flat 属性赋值将导致整个数组的元素都被覆盖
b

# 数组的转换
.tolist()  
.astype()  

In [44]:
f.tolist()  #将NumPy数组转换成Python列表

[(2+1j), (4+3j)]

In [42]:
f.astype(int)  #在转换数组时指定数据类型

/opt/conda/envs/tf1.14.0_py3.7.3/lib/python3.7/site-packages/ipykernel_launcher.py:1: ComplexWarning: Casting complex values to real discards the imaginary part
  """Entry point for launching an IPython kernel.


array([2, 4])