In [58]:
import numpy as np
import sys
from matplotlib.pyplot import plot
from matplotlib.pyplot import show


# 文件读写
np.savetxt()  
np.loadtxt()

In [2]:
a = np.eye(3)
a

In [3]:
np.savetxt("eye.txt", a)

In [4]:
b = np.loadtxt('eye.txt')
b

In [5]:
c = np.loadtxt('data.csv', delimiter=',', usecols=(6,7), unpack=True)
# delimiter 设置分隔符
# usecols   获取字段
# unpack    拆分储存不同列的数据
c

# 常用函数
np.where()  #　根据指定的条件返回所有满足条件的数组元素的索引值,返回的是一个多元数组  
np.take()   #　获取指定索引值相应的元素值  
np.argmax() #　数组中最大元素的索引值  
np.argmax() #　数组中最大元素的索引值  
np.apply_along_axis(） # 调用另外一个由我们给出的函数,作用于每一个数组元素上  
np.maximum() # 在一组数组之间按照元素挑选最大值  
np.minimum() # 在一组数组之间按照元素挑选最小值  
np.linalg.lstsq(A, b) #　返回Ax=b的系数向量 x 、一个残差数组、 A 的秩以及 A 的奇异值  
np.intersect1d()    # 函数返回一个由两个数组的所有公共元素构成的数组

# 计算函数
np.average()    # 平均值    
np.mean()   ＃　算术平均值  
np.max()    ＃　最大值  
np.min()    ＃　最小值  
np.ptp()    ＃　取值范围，返回max()-min()   
np.median() ＃　中位数，长度为偶数的数组,中位数的值应该等于中间那两个数的平均值  
np.msort()  #　数组排序    
np.var()    #　方差   
np.std()    #　标准差  
np.diff()   #　返回一个由相邻数组元素的差值构成的数组   
np.log()    #　取对数  
np.where()  #　根据指定的条件返回所有满足条件的数组元素的索引值  
np.sqrt()   #　平方根（使用浮点数除法）  
np.convolve(） # 一维卷积  
np.exp()    # 函数可以计算出每个数组元素的指数  
np.linspace()  # 返回一个元素值在指定的范围内均匀分布的数组  
np.dot()    # 点积  
.prod   # 计算数组中所有元素的乘积  
.cumprod    # 计算数组元素的累积乘积  

---
# 动手实践

## 简单统计分析

In [6]:
c=np.loadtxt("NumPy Learning/Code/ch3code/data.csv", delimiter=',', usecols=(6,), unpack=True)
print("median =", np.median(c))
sorted = np.msort(c)
print("sorted =", sorted)
N = len(c)
# list　和　ndarray 的索引都必须是整数
# // 取整除，返回商的整数部分（向下取整）
print("middle =", sorted[ (N-1) // 2 ])
print("average middle =", (sorted[N // 2] + sorted[(N - 1) //2]) / 2)
print("variance =", np.var(c))
print("variance from definition =", np.mean((c - c.mean())**2))


## 分析股票收益率

In [7]:
c=np.loadtxt('NumPy Learning/Code/ch3code/data.csv', delimiter=',', usecols=(6,), unpack=True)

# 简单收益率
# c[:-1] 从c[0]开始到c[-1-1]结束,这样去掉了最后一个元素
# ndarray 数组相除，数组中的对应元素依次相除
returns = np.diff( c ) / c[ : -1]
# 标准差
print("Standard deviation =", np.std(returns))
# 对数收益率
logreturns = np.diff( np.log(c) )

# 哪些交易日的收益率为正值
posretindices = np.where(returns > 0)
print("Indices with positive returns", posretindices)

# 年波动率等于对数收益率的标准差除以其均值,再除以交易日倒数的平方根
annual_volatility = np.std(logreturns)/np.mean(logreturns)
annual_volatility = annual_volatility / np.sqrt(1./252.)
print("Annual volatility", annual_volatility)
# 月波动率
print("Monthly volatility", annual_volatility * np.sqrt(1./12.))

## 分析日期数据
首先,我们要读入收盘价数据。随后,根据星期几来切分收盘价数据,并分别计算平均价格。
最后,我们将找出一周中哪一天的平均收盘价最高,哪一天的最低。

In [9]:
from datetime import datetime
# 星期一 0
# 星期二 1
# 星期三 2
# 星期四 3
# 星期五 4
# 星期六 5
# 星期日 6
def datestr2num(s):
    # 是以二进制编码的格式打开第二列值是，返回的值字节字符串bytes，所以需要把它变回string，则对字符串解码用函数decode('asii')，变成string格式。
    return datetime.strptime(s.decode('ascii'),'%d-%m-%Y').date().weekday()

# converters 是一个字典, 表示第1列使用函数datestr2num来进行预处理
dates, close=np.loadtxt('NumPy Learning/Code/ch3code/data.csv', delimiter=',', usecols=(1,6), converters={1:datestr2num}, unpack=True)
print("Dates =", dates)

averages = np.zeros(5)
for i in range(5):
    indices = np.where(dates == i)
    # 用 take 函数获取这些索引值相应的元素值
    prices = np.take(close, indices)
    avg = np.mean(prices)
    print("Day", i, "prices", prices, "Average", avg)
    averages[i] = avg

# 找出哪个工作日的平均收盘价是最高的,哪个是最低的
top = np.max(averages)
print("Highest average", top)
# argmax 函数返回的是 averages 数组中最大元素的索引值
print("Top day of the week", np.argmax(averages))
bottom = np.min(averages)
print("Lowest average", bottom)
# argmin 函数返回的是 averages 数组中最小元素的索引值
print("Bottom day of the week", np.argmin(averages))

## 周汇总

In [26]:
dates, open, high, low, close = np.loadtxt('NumPy Learning/Code/ch3code/data.csv', delimiter=',', converters={1:datestr2num}, usecols=(1,3,4,5,6), unpack=True)
# 只取前3周
close = close[:16]
dates = dates[:16]

# 找到第一个周一
first_Monday = np.ravel(np.where(dates == 0))[0]
print("The first Monday index is", first_Monday)
# 找到最后一个周五
last_Friday = np.ravel(np.where(dates == 4))[-1]
print("The last Friday index is", last_Friday)

# 存储三周内每一天的索引值
weeks_indices = np.arange(first_Monday, last_Friday+1)
print("Weeks indices initial", weeks_indices)
# 按周切分
weeks_indices = np.split(weeks_indices, 3)
print("Weeks indices after split", weeks_indices)

# summarize 函数
# 将为每一周的数据返回一个元组,包含这一周的开盘价、最高价、最低价和收盘价,类似于每天的盘后数据
def summarize(object, open, high, low, close):
    monday_open = open[object[0]]
    week_hight = np.max(np.take(high, object))
    week_low = np.min(np.take(low, object))
    friday_close = close[object[-1]]

    return("APPL", monday_open, week_hight,week_low,friday_close)

# apply_along_axis 函数会调用另外一个由我们给出的函数,作用于每一个数组元素上
#在调用apply_along_axis 时提供我们自定义的函数名 summarize ,并指定要作用的轴或维度的编号(如取1)、目标数组以及可变数量的 summarize 函数的参数
weeksummary = np.apply_along_axis(summarize, 1, weeks_indices, open, high, low, close)
print("Week summary", weeksummary)

# 保存
# fmt 保存的格式
np.savetxt("NumPy Learning/weeksummary.csv", weeksummary, delimiter=",", fmt="%s")

## 真实波动幅度均值(ATR)

In [30]:
high, low, close = np.loadtxt("NumPy Learning/Code/ch3code/data.csv", delimiter=',', usecols=(4,5,6), unpack=True)

# sys.argv 从程序外部获取参数的桥梁
# 0 程序地址    1 输入的第一个参数
# N = int(sys.argv[1])
N =20
# 取最近N个交易日
high = high[-N:]
low = low[-N]
# 前一个交易日的收盘价
previousclose = close[-N-1:-1]

# 当日股价范围 当日最高价和前一个交易日收盘价之差 前一个交易日收盘价和当日最低价之差
# maximum 函数 在一组数组之间按照元素挑选最大值——也就是在所有的数组中第一个元素的最大值、第二个元素的最大值等
truerange = np.maximum(high-low, high-previousclose, previousclose-low)

atr = np.zeros(N)
atr[0] = np.mean(truerange)

# ATR = [(N-1)PATR+TR]/N
for i in range(1,N):
    atr[i] = (N-1) * atr[i-1] + truerange[i]
    atr[i] /= N

print("ATR", atr)

## 简单移动平均线

一维卷积  
np.convolve(\[1,2,3],\[0,1,0.5])  
  
0 0 1 2 3 0 0  
0.5 1 0  
array(\[0. , 1. , 2.5, 4. , 1.5])  

消除边际效应  
np.convolve(\[1,2,3],\[0,1,0.5],'valid')  
array(\[1. , 2.5, 4. ])  


In [55]:
N = 5
weights = np.ones(N) / N
print("Weights", weights)

c = np.loadtxt("NumPy Learning/Code/ch3code/data.csv", delimiter=',', usecols=(6), unpack=True )
sma = np.convolve(c, weights, 'valid')

t = np.arange(N-1, len(c))
plot(t, c[N-1:], lw=1.0)
plot(t, sma, lw=2.0)
show()

## 指数移动平均线
指数移动平均线使用的权重是指数衰减的  
exp 函数可以计算出每个数组元素的指数  
linspace 函数 返回一个元素值在指定的范围内均匀分布的数组

In [56]:
N = 5
weights = np.exp(np.linspace(-1., 0., N))
# 归一化
weights /= weights.sum()   
print("Weights", weights)

c = np.loadtxt("NumPy Learning/Code/ch3code/data.csv", delimiter=',', usecols=(6,), unpack=True)
ema = np.convolve(c, weights, 'valid')

t = np.arange(N-1, len(c))
plot(t, c[N-1:], lw=1.0)
plot(t, ema, lw=2.0)
show()

## 绘制布林带
fill 函数可以将数组元素的值全部设置为一个指定的标量值  

In [66]:
N = 5
weights = np.exp(np.linspace(-1., 0., N))
# 归一化
weights /= weights.sum()   
print("Weights", weights)

c = np.loadtxt("NumPy Learning/Code/ch3code/data.csv", delimiter=',', usecols=(6,), unpack=True)
sma = np.convolve(c, weights, 'valid')
deviation = []
C =len(c)

for i in range(N-1,C):
    if i+N < C:
        dev = c[i:i+N]
    else:
        dev = c[-N:]

    averages = np.zeros(N)
    averages.fill(sma[i-N-1])
    dev = dev - averages
    dev = dev ** 2
    dev = np.sqrt(np.mean(dev))
    deviation.append(dev)

deviation = 2 * np.array(deviation)
upperBB = sma + deviation
lowerBB = sma - deviation

c_slice = c[N-1:]
between_bands = np.where((c_slice < upperBB) & (c_slice > lowerBB))

print(lowerBB[between_bands])
print(c[between_bands])
print(upperBB[between_bands])
between_bands = len(np.ravel(between_bands))
print("Ratio between bands", float(between_bands)/len(c_slice))

t = np.arange(N - 1, C)
plot(t, c_slice, lw=1.0)
plot(t, sma, lw=2.0)
plot(t, upperBB, lw=3.0)
plot(t, lowerBB, lw=4.0)
show()


## 线性模型
linalg 包是专门用于线性代数计算的  
np.linalg.lstsq(A, b)   #　返回Ax=b的系数向量 x 、一个残差数组、 A 的秩以及 A 的奇异值

intersect1d 函数返回一个由两个数组的所有公共元素构成的数组

In [68]:
b = c[-N:]
b = b[::-1]
print("b", b)

A = np.zeros((N, N), float)
print("Zeros N by N", A)

for i in range(N):
    A[i, ] = c[-N - 1 - i: - 1 - i]

print("A", A)

(x, residuals, rank, s) = np.linalg.lstsq(A, b)

print(x, residuals, rank, s)
print(np.dot(b, x))

In [71]:
def fit_line(t, y):
    A = np.vstack([t, np.ones_like(t)]).T
    return np.linalg.lstsq(A, y)[0]

h, l, c = np.loadtxt('NumPy Learning/Code/ch3code/data.csv', delimiter=',', usecols=(4, 5, 6), unpack=True)
pivots = (h + l + c ) / 3
print("Pivots", pivots)

t = np.arange(len(c))
sa, sb = fit_line(t, pivots - (h - l))
ra, rb = fit_line(t, pivots + (h - l))
support = sa * t + sb
resistance = ra * t + rb
condition = (c > support) & (c < resistance)
print("Condition", condition)
between_bands = np.where(condition)
print(support[between_bands])
print(c[between_bands])
print(resistance[between_bands])
between_bands = len(np.ravel(between_bands))
print("Number points between bands", between_bands)
print("Ratio between bands", float(between_bands)/len(c))

print("Tomorrows support", sa * (t[-1] + 1) + sb)
print("Tomorrows resistance", ra * (t[-1] + 1) + rb)

a1 = c[c > support]
a2 = c[c < resistance]
print("Number of points between bands 2nd approach" ,len(np.intersect1d(a1, a2)))

plot(t, c)
plot(t, support)
plot(t, resistance)
show()

## 数组的修剪和压缩
clip 方法返回一个修剪过的数组,也就是将所有比给定最大值还大的元素全部设为给定
的最大值,而所有比给定最小值还小的元素全部设为给定的最小值  
compress 方法返回一个根据给定条件筛选后的数组。 

In [80]:
a = np.arange(5)
print(a,'\n',"Clipped",a.clip(1,2))
print(a,'\n',"Compressed", a.compress(a>2))

[0 1 2 3 4] 
 Clipped [1 1 2 2 2]
[0 1 2 3 4] 
 Compressed [3 4]


## 阶乘
prod 方法,可以计算数组中所有元素的乘积  
cumprod 方法,计算数组元素的累积乘积

In [83]:
b = np.arange(1, 9)
print(b,'\n', "Factorial", b.prod())
print(b,'\n', "Factorials", b.cumprod())

[1 2 3 4 5 6 7 8] 
 Factorial 40320
[1 2 3 4 5 6 7 8] 
 Factorials [    1     2     6    24   120   720  5040 40320]
